import express from "express";
import cors from "cors";
import { OAuth2Client } from "google-auth-library";
import jwt from "jsonwebtoken";
import Anthropic from "@anthropic-ai/sdk";
import rateLimit from "express-rate-limit";
import { pool } from "./db";

const app = express();
app.use(express.json());
// Render terminates TLS at a proxy; this lets req.ip reflect the real client.
app.set("trust proxy", true);

app.use(cors({ origin: process.env.CORS_ORIGIN ?? "*" }));

// ---- Rate limiting ---------------------------------------------------------
// `trust proxy` is true (Render sits in front), so disable express-rate-limit's
// permissive-proxy guard; IPs come from Render's X-Forwarded-For.
const validate = { trustProxy: false };
const apiLimiter = rateLimit({
  windowMs: 60_000, max: 120, standardHeaders: true, legacyHeaders: false, validate,
  message: { error: "Too many requests — please slow down." },
});
const authLimiter = rateLimit({
  windowMs: 15 * 60_000, max: 30, standardHeaders: true, legacyHeaders: false, validate,
  message: { error: "Too many sign-in attempts — try again later." },
});
const summaryLimiter = rateLimit({
  windowMs: 60_000, max: 15, standardHeaders: true, legacyHeaders: false, validate,
  message: { error: "Too many summary requests — try again shortly." },
});
// /health stays unlimited (Render pings it); everything under /api is capped.
app.use("/api", apiLimiter);

// ---- Config ----------------------------------------------------------------

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const googleClient = new OAuth2Client(GOOGLE_CLIENT_ID);
const JWT_SECRET = process.env.JWT_SECRET ?? "dev-insecure-secret-change-me";

const ADMIN_EMAILS = (process.env.ADMIN_EMAILS ?? "")
  .split(",")
  .map((e) => e.trim().toLowerCase())
  .filter(Boolean);

const isAdminEmail = (email?: string | null) =>
  !!email && ADMIN_EMAILS.includes(email.toLowerCase());

// Summaries can be generated by Google Gemini (free tier) or Claude. Whichever
// key is set wins (Gemini first). If neither is set, the summarize endpoints
// return a clear 503 instead of crashing.
const anthropic = process.env.ANTHROPIC_API_KEY
  ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  : null;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-2.0-flash";
const summariesEnabled = !!GEMINI_API_KEY || !!anthropic;

const SINGLE_SYSTEM =
  "You are an expert meeting assistant. Turn the raw transcript into a clear, " +
  "skimmable summary in Markdown. Respond with only the summary — no preamble.";

const COMBINED_SYSTEM =
  "You are an expert chief of staff. You are given individual summaries of " +
  "several meetings. Synthesize them into one consolidated cross-meeting " +
  "summary in Markdown. Respond with only the summary — no preamble.";

const singlePrompt = (title: string, transcript: string) =>
  `Meeting title: ${title}\n\nTranscript:\n${transcript}\n\n` +
  "Produce exactly these sections:\n" +
  "## Summary\nA 2–4 sentence overview.\n" +
  "## Key points\n- concise bullets\n" +
  '## Decisions\n- decisions made (or "None")\n' +
  '## Action items\n- owner — task with any due date (or "None")';

const combinedPrompt = (blocks: string) =>
  `Here are summaries from several meetings:\n\n${blocks}\n\n` +
  "Write a consolidated summary with these sections:\n" +
  "## Overview\nA short paragraph across all of them.\n" +
  "## Common themes\n- recurring topics\n" +
  "## Key decisions\n- decisions across the meetings\n" +
  "## Consolidated action items\n- owner — task\n" +
  "## Per-meeting highlights\n- **Meeting** — one line each";

// ---- Jira tracking prompts -------------------------------------------------
// Extract what a single meeting concluded about ONE specific Jira ticket.
const JIRA_EXTRACT_SYSTEM =
  "You are a precise program-management analyst. Given a meeting's notes, you " +
  "extract only the part that concerns one specific Jira ticket. Be faithful to " +
  "the source — never invent decisions. Respond with only the requested text.";

const jiraExtractPrompt = (key: string, title: string, content: string) =>
  `Jira ticket: ${key}\nMeeting: ${title}\n\nMeeting notes (summary and/or transcript):\n${content}\n\n` +
  `In 2–4 sentences, describe specifically what was discussed and concluded about ${key} in this meeting — ` +
  `decisions, blockers, owners, and next steps if mentioned. ` +
  `If ${key} was not meaningfully discussed, reply with exactly: Not specifically discussed in this meeting.`;

// Synthesize the whole cross-meeting journey for one Jira ticket.
const JIRA_JOURNEY_SYSTEM =
  "You are a program manager tracking a single Jira ticket across many meetings. " +
  "You are given each meeting's conclusion about the ticket, in chronological order. " +
  "Synthesize the ticket's journey in Markdown. Respond with only the Markdown.";

const jiraJourneyPrompt = (key: string, blocks: string) =>
  `Jira ticket: ${key}\n\nChronological per-meeting conclusions:\n\n${blocks}\n\n` +
  "Write the ticket's journey with exactly these sections:\n" +
  "## Where it stands\nA 2–3 sentence read on the current status.\n" +
  "## Journey\n- date — what was discussed/decided (chronological)\n" +
  "## Key decisions\n- decisions made across the meetings (or \"None\")\n" +
  "## Open questions & next steps\n- bullets (or \"None\")";

// A Jira key looks like PROJ-123 / AB12-4567. Normalize to upper-case.
const JIRA_KEY_RE = /^[A-Z][A-Z0-9]+-\d+$/;
const normalizeJira = (v: unknown): string | null => {
  const k = String(v ?? "").trim().toUpperCase();
  return JIRA_KEY_RE.test(k) ? k : null;
};

/** Single Claude call that returns the joined text of the response. */
async function summarizeWithClaude(system: string, user: string): Promise<string> {
  if (!anthropic) throw new Error("anthropic_not_configured");
  const message = await anthropic.messages.create({
    model: "claude-opus-4-8",
    max_tokens: 2048,
    thinking: { type: "adaptive" },
    output_config: { effort: "medium" },
    system,
    messages: [{ role: "user", content: user }],
  });
  return message.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();
}

/** Single Gemini call (Generative Language API) returning the joined text. */
async function summarizeWithGemini(system: string, user: string): Promise<string> {
  if (!GEMINI_API_KEY) throw new Error("gemini_not_configured");
  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent` +
    `?key=${encodeURIComponent(GEMINI_API_KEY)}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: system }] },
      contents: [{ role: "user", parts: [{ text: user }] }],
      generationConfig: { maxOutputTokens: 2048, temperature: 0.3 },
    }),
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data: any = await res.json();
  const parts = data?.candidates?.[0]?.content?.parts ?? [];
  return parts.map((p: any) => p?.text ?? "").join("").trim();
}

/** Route to whichever summary provider is configured (Gemini preferred). */
async function runSummary(system: string, user: string): Promise<string> {
  if (GEMINI_API_KEY) return summarizeWithGemini(system, user);
  if (anthropic) return summarizeWithClaude(system, user);
  throw new Error("no_summary_provider");
}

// ---- Auth types & middleware -----------------------------------------------

interface SessionUser {
  email: string;
  name: string | null;
  picture: string | null;
  isAdmin: boolean;
}
interface AuthedRequest extends express.Request {
  user?: SessionUser;
}

function signToken(user: SessionUser): string {
  return jwt.sign(user, JWT_SECRET, { expiresIn: "30d" });
}

function requireAuth(
  req: AuthedRequest,
  res: express.Response,
  next: express.NextFunction
) {
  const header = req.headers.authorization ?? "";
  const token = header.startsWith("Bearer ") ? header.slice(7) : "";
  if (!token) return res.status(401).json({ error: "Not authenticated" });
  try {
    req.user = jwt.verify(token, JWT_SECRET) as SessionUser;
    next();
  } catch {
    return res.status(401).json({ error: "Session expired, please sign in again" });
  }
}

function requireAdmin(
  req: AuthedRequest,
  res: express.Response,
  next: express.NextFunction
) {
  requireAuth(req, res, () => {
    if (!req.user?.isAdmin) return res.status(403).json({ error: "Admins only" });
    next();
  });
}

const nullIfEmpty = (v: unknown) =>
  v === "" || v === undefined ? null : v;

// ---- Health ----------------------------------------------------------------

app.get("/health", (_req, res) => res.json({ status: "ok" }));

// ---- Auth: Sign in with Google ---------------------------------------------

app.post("/api/auth/google", authLimiter, async (req, res) => {
  const { credential } = req.body ?? {};
  if (!credential) return res.status(400).json({ error: "credential is required" });
  if (!GOOGLE_CLIENT_ID)
    return res.status(500).json({ error: "Server is not configured for Google login" });

  try {
    const ticket = await googleClient.verifyIdToken({
      idToken: credential,
      audience: GOOGLE_CLIENT_ID,
    });
    const payload = ticket.getPayload();
    if (!payload?.sub || !payload.email)
      return res.status(401).json({ error: "Invalid Google token" });

    const { sub, email, name, picture } = payload;
    const admin = isAdminEmail(email);

    const userResult = await pool.query(
      `INSERT INTO users (google_sub, email, name, picture)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (google_sub)
       DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, picture = EXCLUDED.picture
       RETURNING id, access_enabled`,
      [sub, email, name ?? null, picture ?? null]
    );
    if (!userResult.rows[0].access_enabled && !admin)
      return res
        .status(403)
        .json({ error: "Your access has been disabled by the administrator." });

    const ip = (req.headers["x-forwarded-for"] as string) || req.ip || null;
    await pool.query(
      `INSERT INTO logins (user_id, email, name, ip, user_agent)
       VALUES ($1, $2, $3, $4, $5)`,
      [userResult.rows[0].id, email, name ?? null, ip, req.headers["user-agent"] ?? null]
    );

    const user: SessionUser = {
      email,
      name: name ?? null,
      picture: picture ?? null,
      isAdmin: admin,
    };
    res.json({ token: signToken(user), user });
  } catch (err) {
    console.error("Google login failed:", err);
    res.status(401).json({ error: "Invalid Google token" });
  }
});

// Return the current user from the session token (used on app load).
app.get("/api/me", requireAuth, (req: AuthedRequest, res) => res.json(req.user));

// ---- User settings (per-user preferences) ----------------------------------

app.get("/api/settings", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const r = await pool.query(
      "SELECT jira_base_url FROM users WHERE email = $1 ORDER BY id DESC LIMIT 1",
      [req.user!.email]
    );
    res.json({ jira_base_url: r.rows[0]?.jira_base_url ?? null });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch settings" });
  }
});

app.patch("/api/settings", requireAuth, async (req: AuthedRequest, res) => {
  const raw = req.body?.jira_base_url;
  // Normalize: trim, require http(s), ensure a single trailing slash so the
  // client can just append the key. Empty string clears it.
  let url: string | null = null;
  if (typeof raw === "string" && raw.trim()) {
    const t = raw.trim();
    if (!/^https?:\/\//i.test(t))
      return res.status(400).json({ error: "Jira base URL must start with http:// or https://" });
    url = t.replace(/\/+$/, "") + "/";
  }
  try {
    await pool.query("UPDATE users SET jira_base_url = $1 WHERE email = $2", [url, req.user!.email]);
    res.json({ jira_base_url: url });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to save settings" });
  }
});

// ---- Meetings --------------------------------------------------------------

app.get("/api/meetings", requireAuth, async (req: AuthedRequest, res) => {
  const { status, q } = req.query as { status?: string; q?: string };
  const params: any[] = [req.user!.email];
  // array_agg of linked Jira keys so the list/board can show & filter by ticket.
  let sql =
    `SELECT m.*,
       COALESCE(ARRAY_AGG(mj.jira_key ORDER BY mj.jira_key) FILTER (WHERE mj.jira_key IS NOT NULL), '{}') AS jira_keys
     FROM meetings m
     LEFT JOIN meeting_jiras mj ON mj.meeting_id = m.id AND mj.user_email = m.user_email
     WHERE m.user_email = $1`;
  if (status && status !== "all") {
    params.push(status);
    sql += ` AND m.status = $${params.length}`;
  }
  if (q) {
    params.push(`%${q}%`);
    sql += ` AND (m.title ILIKE $${params.length} OR m.attendees ILIKE $${params.length} OR m.notes ILIKE $${params.length})`;
  }
  sql += " GROUP BY m.id ORDER BY m.meeting_date DESC NULLS LAST, m.created_at DESC";
  try {
    res.json((await pool.query(sql, params)).rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch meetings" });
  }
});

app.post("/api/meetings", requireAuth, async (req: AuthedRequest, res) => {
  const { title, meeting_date, attendees, meet_link, notes, status } = req.body ?? {};
  if (!title?.trim()) return res.status(400).json({ error: "title is required" });
  try {
    const result = await pool.query(
      `INSERT INTO meetings (user_email, title, meeting_date, attendees, meet_link, notes, summary, status)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,
      [
        req.user!.email,
        title.trim(),
        nullIfEmpty(meeting_date),
        nullIfEmpty(attendees),
        nullIfEmpty(meet_link),
        nullIfEmpty(notes),
        notes ? String(notes).slice(0, 200) : null,
        status || "upcoming",
      ]
    );
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to create meeting" });
  }
});

app.patch("/api/meetings/:id", requireAuth, async (req: AuthedRequest, res) => {
  const allowed = ["title", "meeting_date", "attendees", "meet_link", "notes", "summary", "transcript", "status", "google_event_id", "rsvp"];
  const sets: string[] = [];
  const vals: any[] = [];
  for (const f of allowed) {
    if (f in req.body) {
      // rsvp is JSONB — store it as JSON text.
      vals.push(f === "rsvp" ? JSON.stringify(req.body[f]) : nullIfEmpty(req.body[f]));
      sets.push(`${f} = $${vals.length}`);
    }
  }
  if (!sets.length) return res.status(400).json({ error: "No fields to update" });
  vals.push(Number(req.params.id), req.user!.email);
  try {
    const result = await pool.query(
      `UPDATE meetings SET ${sets.join(", ")}
       WHERE id = $${vals.length - 1} AND user_email = $${vals.length} RETURNING *`,
      vals
    );
    if (!result.rowCount) return res.status(404).json({ error: "Not found" });
    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to update meeting" });
  }
});

app.delete("/api/meetings/:id", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const result = await pool.query(
      "DELETE FROM meetings WHERE id = $1 AND user_email = $2",
      [Number(req.params.id), req.user!.email]
    );
    if (!result.rowCount) return res.status(404).json({ error: "Not found" });
    res.json({ ok: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to delete meeting" });
  }
});

// Turn a meeting transcript into a summary with Claude, then store both and
// mark the meeting completed. The transcript itself is fetched by the frontend
// from the Google Meet API and POSTed here.
app.post("/api/meetings/:id/summarize", summaryLimiter, requireAuth, async (req: AuthedRequest, res) => {
  if (!summariesEnabled)
    return res
      .status(503)
      .json({ error: "Summaries aren't configured on the server (set GEMINI_API_KEY or ANTHROPIC_API_KEY)." });

  const transcript = String(req.body?.transcript ?? "").trim();
  if (!transcript) return res.status(400).json({ error: "transcript is required" });

  const id = Number(req.params.id);
  try {
    const owned = await pool.query(
      "SELECT title FROM meetings WHERE id = $1 AND user_email = $2",
      [id, req.user!.email]
    );
    if (!owned.rowCount) return res.status(404).json({ error: "Not found" });

    // Bound the transcript so a very long call can't blow up the request.
    const text = transcript.slice(0, 100_000);
    const summary = await runSummary(SINGLE_SYSTEM, singlePrompt(owned.rows[0].title, text));

    if (!summary) return res.status(502).json({ error: "Empty summary from the model." });

    const updated = await pool.query(
      `UPDATE meetings SET summary = $1, transcript = $2, status = 'completed'
       WHERE id = $3 AND user_email = $4 RETURNING *`,
      [summary, text, id, req.user!.email]
    );
    res.json(updated.rows[0]);
  } catch (err) {
    console.error("Summarize failed:", err);
    res.status(502).json({ error: "Could not generate the summary. Please try again." });
  }
});

// ---- Per-occurrence sessions (one Meet conference = one session) ------------
// The same Meet link can host many conferences over time; each becomes its own
// session row so you get an individual transcript + summary per occurrence.

app.get("/api/meetings/:id/sessions", requireAuth, async (req: AuthedRequest, res) => {
  const id = Number(req.params.id);
  try {
    const r = await pool.query(
      `SELECT id, conference_record, started_at, ended_at, transcript, summary, created_at
       FROM meeting_sessions WHERE meeting_id = $1 AND user_email = $2
       ORDER BY ended_at DESC NULLS LAST, id DESC`,
      [id, req.user!.email]
    );
    res.json(r.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch sessions" });
  }
});

app.post("/api/meetings/:id/sessions", summaryLimiter, requireAuth, async (req: AuthedRequest, res) => {
  if (!summariesEnabled)
    return res
      .status(503)
      .json({ error: "Summaries aren't configured on the server (set GEMINI_API_KEY or ANTHROPIC_API_KEY)." });

  const id = Number(req.params.id);
  const { conference_record, started_at, ended_at } = req.body ?? {};
  const transcript = String(req.body?.transcript ?? "").trim();
  if (!conference_record || !transcript)
    return res.status(400).json({ error: "conference_record and transcript are required" });

  try {
    const owned = await pool.query(
      "SELECT title FROM meetings WHERE id = $1 AND user_email = $2",
      [id, req.user!.email]
    );
    if (!owned.rowCount) return res.status(404).json({ error: "Not found" });

    const text = transcript.slice(0, 100_000);
    const summary = await runSummary(SINGLE_SYSTEM, singlePrompt(owned.rows[0].title, text));
    if (!summary) return res.status(502).json({ error: "Empty summary from the model." });

    const up = await pool.query(
      `INSERT INTO meeting_sessions
         (meeting_id, user_email, conference_record, started_at, ended_at, transcript, summary)
       VALUES ($1,$2,$3,$4,$5,$6,$7)
       ON CONFLICT (meeting_id, conference_record) DO UPDATE SET
         started_at = EXCLUDED.started_at, ended_at = EXCLUDED.ended_at,
         transcript = EXCLUDED.transcript, summary = EXCLUDED.summary
       RETURNING id, conference_record, started_at, ended_at, transcript, summary, created_at`,
      [id, req.user!.email, conference_record, nullIfEmpty(started_at), nullIfEmpty(ended_at), text, summary]
    );

    // Mirror the most recent session onto the meeting row for quick display.
    await pool.query(
      `UPDATE meetings m SET summary = s.summary, transcript = s.transcript, status = 'completed'
       FROM (SELECT summary, transcript FROM meeting_sessions
             WHERE meeting_id = $1 ORDER BY ended_at DESC NULLS LAST, id DESC LIMIT 1) s
       WHERE m.id = $1 AND m.user_email = $2`,
      [id, req.user!.email]
    );

    res.json(up.rows[0]);
  } catch (err) {
    console.error("Add session failed:", err);
    res.status(502).json({ error: "Could not summarize this session." });
  }
});

// ---- Combined summary across several meetings -------------------------------

app.post("/api/meetings/combined-summary", summaryLimiter, requireAuth, async (req: AuthedRequest, res) => {
  if (!summariesEnabled)
    return res
      .status(503)
      .json({ error: "Summaries aren't configured on the server (set GEMINI_API_KEY or ANTHROPIC_API_KEY)." });

  const ids: number[] = Array.isArray(req.body?.meeting_ids)
    ? req.body.meeting_ids.map(Number).filter(Number.isInteger)
    : [];
  if (ids.length < 2)
    return res.status(400).json({ error: "Select at least two meetings to combine." });

  try {
    const email = req.user!.email;
    const [meetings, sessions] = await Promise.all([
      pool.query(`SELECT id, title, summary FROM meetings WHERE user_email = $1 AND id = ANY($2::int[])`, [email, ids]),
      pool.query(
        `SELECT meeting_id, summary FROM meeting_sessions
         WHERE user_email = $1 AND meeting_id = ANY($2::int[]) AND summary IS NOT NULL
         ORDER BY ended_at ASC NULLS LAST, id ASC`,
        [email, ids]
      ),
    ]);
    if (!meetings.rowCount) return res.status(404).json({ error: "No meetings found." });

    const byMeeting = new Map<number, string[]>();
    for (const s of sessions.rows) {
      if (!byMeeting.has(s.meeting_id)) byMeeting.set(s.meeting_id, []);
      byMeeting.get(s.meeting_id)!.push(s.summary);
    }

    const blocks: string[] = [];
    for (const m of meetings.rows) {
      const parts = byMeeting.get(m.id) ?? (m.summary ? [m.summary] : []);
      if (parts.length) blocks.push(`## ${m.title}\n${parts.join("\n\n---\n")}`);
    }
    if (!blocks.length)
      return res.status(400).json({ error: "None of the selected meetings have a summary yet." });

    const summary = await runSummary(COMBINED_SYSTEM, combinedPrompt(blocks.join("\n\n")));
    if (!summary) return res.status(502).json({ error: "Empty summary from the model." });
    res.json({ summary });
  } catch (err) {
    console.error("Combined summary failed:", err);
    res.status(502).json({ error: "Could not build the combined summary." });
  }
});

// ---- Jira tracking ---------------------------------------------------------
// Tickets are entered manually (one meeting ↔ many tickets, one ticket ↔ many
// meetings). For each link we cache an AI-extracted conclusion: what THIS
// meeting decided about THAT ticket. Per ticket we can synthesize the whole
// cross-meeting journey.

// Build the "what did this meeting conclude about this ticket" text. Returns
// null when there's nothing to read or no summary provider is configured.
async function extractJiraConclusion(
  email: string,
  meetingId: number,
  jiraKey: string
): Promise<string | null> {
  if (!summariesEnabled) return null;
  const r = await pool.query(
    "SELECT title, summary, transcript FROM meetings WHERE id = $1 AND user_email = $2",
    [meetingId, email]
  );
  if (!r.rowCount) return null;
  const { title, summary, transcript } = r.rows[0];
  const content =
    (summary ? `Summary:\n${summary}\n\n` : "") +
    (transcript ? `Transcript:\n${String(transcript).slice(0, 60_000)}` : "");
  if (!content.trim()) return null;
  try {
    const out = await runSummary(JIRA_EXTRACT_SYSTEM, jiraExtractPrompt(jiraKey, title ?? "Meeting", content));
    return out?.trim() || null;
  } catch (err) {
    console.error("Jira conclusion extraction failed:", err);
    return null;
  }
}

// List of distinct tickets with rollups (used by the Jira board).
app.get("/api/jiras", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const r = await pool.query(
      `SELECT mj.jira_key,
         COUNT(DISTINCT mj.meeting_id)::int AS meeting_count,
         COUNT(mj.conclusion)::int          AS with_conclusion,
         MIN(m.meeting_date)                AS first_discussed,
         MAX(m.meeting_date)                AS last_discussed,
         j.title,
         (j.journey_summary IS NOT NULL)    AS has_journey,
         j.journey_built_at
       FROM meeting_jiras mj
       JOIN meetings m ON m.id = mj.meeting_id AND m.user_email = mj.user_email
       LEFT JOIN jiras j ON j.user_email = mj.user_email AND j.jira_key = mj.jira_key
       WHERE mj.user_email = $1
       GROUP BY mj.jira_key, j.title, j.journey_summary, j.journey_built_at
       ORDER BY MAX(m.meeting_date) DESC NULLS LAST, mj.jira_key`,
      [req.user!.email]
    );
    res.json(r.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch Jira tickets" });
  }
});

// Mind-map data: every ticket, every meeting that has ≥1 ticket, and the links.
app.get("/api/jira-map", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const email = req.user!.email;
    const [jiras, meetings, edges] = await Promise.all([
      pool.query(
        `SELECT mj.jira_key, COUNT(DISTINCT mj.meeting_id)::int AS meeting_count, j.title
         FROM meeting_jiras mj
         LEFT JOIN jiras j ON j.user_email = mj.user_email AND j.jira_key = mj.jira_key
         WHERE mj.user_email = $1 GROUP BY mj.jira_key, j.title`,
        [email]
      ),
      pool.query(
        `SELECT DISTINCT m.id, m.title, m.meeting_date
         FROM meetings m JOIN meeting_jiras mj ON mj.meeting_id = m.id AND mj.user_email = m.user_email
         WHERE m.user_email = $1`,
        [email]
      ),
      pool.query(
        "SELECT meeting_id, jira_key FROM meeting_jiras WHERE user_email = $1",
        [email]
      ),
    ]);
    res.json({ jiras: jiras.rows, meetings: meetings.rows, edges: edges.rows });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to build Jira map" });
  }
});

// One ticket: metadata + chronological meeting journey with per-meeting conclusions.
app.get("/api/jiras/:key", requireAuth, async (req: AuthedRequest, res) => {
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  try {
    const email = req.user!.email;
    const [meta, meetings, settings] = await Promise.all([
      pool.query("SELECT title, journey_summary, journey_built_at FROM jiras WHERE user_email = $1 AND jira_key = $2", [email, key]),
      pool.query(
        `SELECT m.id, m.title, m.meeting_date, m.meet_link, m.status,
                (m.summary IS NOT NULL) AS has_summary, mj.conclusion
         FROM meeting_jiras mj
         JOIN meetings m ON m.id = mj.meeting_id AND m.user_email = mj.user_email
         WHERE mj.user_email = $1 AND mj.jira_key = $2
         ORDER BY m.meeting_date ASC NULLS LAST, m.id ASC`,
        [email, key]
      ),
      pool.query("SELECT jira_base_url FROM users WHERE email = $1 ORDER BY id DESC LIMIT 1", [email]),
    ]);
    if (!meetings.rowCount) return res.status(404).json({ error: "No meetings reference this ticket." });
    res.json({
      jira_key: key,
      title: meta.rows[0]?.title ?? null,
      journey_summary: meta.rows[0]?.journey_summary ?? null,
      journey_built_at: meta.rows[0]?.journey_built_at ?? null,
      base_url: settings.rows[0]?.jira_base_url ?? null,
      meetings: meetings.rows,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch ticket" });
  }
});

// Set a human title for a ticket (upsert).
app.patch("/api/jiras/:key", requireAuth, async (req: AuthedRequest, res) => {
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  const title = nullIfEmpty(req.body?.title);
  try {
    const r = await pool.query(
      `INSERT INTO jiras (user_email, jira_key, title) VALUES ($1, $2, $3)
       ON CONFLICT (user_email, jira_key) DO UPDATE SET title = EXCLUDED.title
       RETURNING jira_key, title`,
      [req.user!.email, key, title]
    );
    res.json(r.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to update ticket" });
  }
});

// Synthesize the whole journey for a ticket from its per-meeting conclusions.
app.post("/api/jiras/:key/synthesize", summaryLimiter, requireAuth, async (req: AuthedRequest, res) => {
  if (!summariesEnabled)
    return res.status(503).json({ error: "Summaries aren't configured on the server (set GEMINI_API_KEY or ANTHROPIC_API_KEY)." });
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  try {
    const email = req.user!.email;
    const rows = (await pool.query(
      `SELECT m.title, m.meeting_date, mj.conclusion
       FROM meeting_jiras mj
       JOIN meetings m ON m.id = mj.meeting_id AND m.user_email = mj.user_email
       WHERE mj.user_email = $1 AND mj.jira_key = $2 AND mj.conclusion IS NOT NULL
       ORDER BY m.meeting_date ASC NULLS LAST, m.id ASC`,
      [email, key]
    )).rows;
    if (!rows.length)
      return res.status(400).json({ error: "No per-meeting conclusions yet. Tag meetings (and let conclusions generate) first." });

    const blocks = rows.map((r) => {
      const d = r.meeting_date ? new Date(r.meeting_date).toISOString().slice(0, 10) : "undated";
      return `- ${d} — ${r.title}: ${r.conclusion}`;
    }).join("\n");

    const summary = await runSummary(JIRA_JOURNEY_SYSTEM, jiraJourneyPrompt(key, blocks));
    if (!summary) return res.status(502).json({ error: "Empty summary from the model." });

    const r = await pool.query(
      `INSERT INTO jiras (user_email, jira_key, journey_summary, journey_built_at)
       VALUES ($1, $2, $3, now())
       ON CONFLICT (user_email, jira_key)
       DO UPDATE SET journey_summary = EXCLUDED.journey_summary, journey_built_at = now()
       RETURNING journey_summary, journey_built_at`,
      [email, key, summary]
    );
    res.json(r.rows[0]);
  } catch (err) {
    console.error("Jira journey synthesis failed:", err);
    res.status(502).json({ error: "Could not build the journey summary." });
  }
});

// Tickets linked to one meeting (for the meeting detail page).
app.get("/api/meetings/:id/jiras", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const r = await pool.query(
      "SELECT jira_key, conclusion FROM meeting_jiras WHERE meeting_id = $1 AND user_email = $2 ORDER BY jira_key",
      [Number(req.params.id), req.user!.email]
    );
    res.json(r.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch ticket links" });
  }
});

// Attach a ticket to a meeting; best-effort auto-extract the conclusion.
app.post("/api/meetings/:id/jiras", requireAuth, async (req: AuthedRequest, res) => {
  const id = Number(req.params.id);
  const key = normalizeJira(req.body?.jira_key);
  if (!key) return res.status(400).json({ error: "Provide a valid Jira key like PROJ-123." });
  try {
    const email = req.user!.email;
    const owned = await pool.query("SELECT id FROM meetings WHERE id = $1 AND user_email = $2", [id, email]);
    if (!owned.rowCount) return res.status(404).json({ error: "Meeting not found" });

    const conclusion = await extractJiraConclusion(email, id, key);
    const r = await pool.query(
      `INSERT INTO meeting_jiras (meeting_id, user_email, jira_key, conclusion)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (meeting_id, jira_key, user_email)
       DO UPDATE SET conclusion = COALESCE(EXCLUDED.conclusion, meeting_jiras.conclusion)
       RETURNING jira_key, conclusion`,
      [id, email, key, conclusion]
    );
    // Make sure the ticket exists in the jiras table so it shows on the board.
    await pool.query(
      "INSERT INTO jiras (user_email, jira_key) VALUES ($1, $2) ON CONFLICT (user_email, jira_key) DO NOTHING",
      [email, key]
    );
    res.status(201).json(r.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to link ticket" });
  }
});

// Manually edit a meeting's conclusion about a ticket.
app.patch("/api/meetings/:id/jiras/:key", requireAuth, async (req: AuthedRequest, res) => {
  const id = Number(req.params.id);
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  try {
    const r = await pool.query(
      `UPDATE meeting_jiras SET conclusion = $1
       WHERE meeting_id = $2 AND jira_key = $3 AND user_email = $4
       RETURNING jira_key, conclusion`,
      [nullIfEmpty(req.body?.conclusion), id, key, req.user!.email]
    );
    if (!r.rowCount) return res.status(404).json({ error: "Link not found" });
    res.json(r.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to update conclusion" });
  }
});

// Re-run AI extraction for one meeting+ticket conclusion.
app.post("/api/meetings/:id/jiras/:key/extract", summaryLimiter, requireAuth, async (req: AuthedRequest, res) => {
  if (!summariesEnabled)
    return res.status(503).json({ error: "Summaries aren't configured on the server (set GEMINI_API_KEY or ANTHROPIC_API_KEY)." });
  const id = Number(req.params.id);
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  try {
    const email = req.user!.email;
    const conclusion = await extractJiraConclusion(email, id, key);
    if (!conclusion) return res.status(400).json({ error: "This meeting has no summary or transcript to read yet." });
    const r = await pool.query(
      `UPDATE meeting_jiras SET conclusion = $1
       WHERE meeting_id = $2 AND jira_key = $3 AND user_email = $4
       RETURNING jira_key, conclusion`,
      [conclusion, id, key, email]
    );
    if (!r.rowCount) return res.status(404).json({ error: "Link not found" });
    res.json(r.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(502).json({ error: "Could not extract the conclusion." });
  }
});

// Detach a ticket from a meeting.
app.delete("/api/meetings/:id/jiras/:key", requireAuth, async (req: AuthedRequest, res) => {
  const key = normalizeJira(req.params.key);
  if (!key) return res.status(400).json({ error: "Invalid Jira key" });
  try {
    const r = await pool.query(
      "DELETE FROM meeting_jiras WHERE meeting_id = $1 AND jira_key = $2 AND user_email = $3",
      [Number(req.params.id), key, req.user!.email]
    );
    if (!r.rowCount) return res.status(404).json({ error: "Link not found" });
    res.json({ ok: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to unlink ticket" });
  }
});

// ---- Tasks (action items) --------------------------------------------------

app.get("/api/tasks", requireAuth, async (req: AuthedRequest, res) => {
  const { done, meeting_id } = req.query as { done?: string; meeting_id?: string };
  const params: any[] = [req.user!.email];
  let sql =
    `SELECT t.*, m.title AS meeting_title
     FROM tasks t LEFT JOIN meetings m ON m.id = t.meeting_id
     WHERE t.user_email = $1`;
  if (done === "true" || done === "false") {
    params.push(done === "true");
    sql += ` AND t.done = $${params.length}`;
  }
  if (meeting_id) {
    params.push(Number(meeting_id));
    sql += ` AND t.meeting_id = $${params.length}`;
  }
  sql += " ORDER BY t.done ASC, t.due_date ASC NULLS LAST, t.created_at DESC";
  try {
    res.json((await pool.query(sql, params)).rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch tasks" });
  }
});

app.post("/api/tasks", requireAuth, async (req: AuthedRequest, res) => {
  const { title, priority, due_date, meeting_id } = req.body ?? {};
  if (!title?.trim()) return res.status(400).json({ error: "title is required" });
  try {
    const result = await pool.query(
      `INSERT INTO tasks (user_email, title, priority, due_date, meeting_id)
       VALUES ($1,$2,$3,$4,$5) RETURNING *`,
      [
        req.user!.email,
        title.trim(),
        priority || "medium",
        nullIfEmpty(due_date),
        nullIfEmpty(meeting_id),
      ]
    );
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to create task" });
  }
});

app.patch("/api/tasks/:id", requireAuth, async (req: AuthedRequest, res) => {
  const allowed = ["title", "done", "priority", "due_date", "meeting_id"];
  const sets: string[] = [];
  const vals: any[] = [];
  for (const f of allowed) {
    if (f in req.body) {
      vals.push(f === "done" ? !!req.body[f] : nullIfEmpty(req.body[f]));
      sets.push(`${f} = $${vals.length}`);
    }
  }
  if (!sets.length) return res.status(400).json({ error: "No fields to update" });
  vals.push(Number(req.params.id), req.user!.email);
  try {
    const result = await pool.query(
      `UPDATE tasks SET ${sets.join(", ")}
       WHERE id = $${vals.length - 1} AND user_email = $${vals.length} RETURNING *`,
      vals
    );
    if (!result.rowCount) return res.status(404).json({ error: "Not found" });
    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to update task" });
  }
});

app.delete("/api/tasks/:id", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const result = await pool.query(
      "DELETE FROM tasks WHERE id = $1 AND user_email = $2",
      [Number(req.params.id), req.user!.email]
    );
    if (!result.rowCount) return res.status(404).json({ error: "Not found" });
    res.json({ ok: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to delete task" });
  }
});

// ---- Dashboard stats -------------------------------------------------------

app.get("/api/stats", requireAuth, async (req: AuthedRequest, res) => {
  try {
    const email = req.user!.email;
    const [m, t] = await Promise.all([
      pool.query(
        `SELECT
           COUNT(*)::int AS total,
           COUNT(*) FILTER (WHERE status = 'upcoming')::int AS upcoming,
           COUNT(*) FILTER (WHERE status = 'completed')::int AS completed
         FROM meetings WHERE user_email = $1`,
        [email]
      ),
      pool.query(
        `SELECT
           COUNT(*) FILTER (WHERE NOT done)::int AS open,
           COUNT(*) FILTER (WHERE done)::int AS done
         FROM tasks WHERE user_email = $1`,
        [email]
      ),
    ]);
    res.json({ meetings: m.rows[0], tasks: t.rows[0] });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch stats" });
  }
});

// ---- Admin -----------------------------------------------------------------

app.get("/api/admin/users", requireAdmin, async (_req, res) => {
  try {
    res.json(
      (
        await pool.query(
          `SELECT id, email, name, picture, access_enabled, created_at
           FROM users ORDER BY created_at DESC`
        )
      ).rows
    );
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch users" });
  }
});

app.get("/api/admin/logins", requireAdmin, async (_req, res) => {
  try {
    res.json(
      (
        await pool.query(
          `SELECT id, email, name, ip, user_agent, logged_in_at
           FROM logins ORDER BY logged_in_at DESC LIMIT 500`
        )
      ).rows
    );
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch logins" });
  }
});

app.patch("/api/admin/users/:id/access", requireAdmin, async (req, res) => {
  const id = Number(req.params.id);
  const { enabled } = req.body ?? {};
  if (!Number.isInteger(id) || typeof enabled !== "boolean")
    return res.status(400).json({ error: "id and boolean 'enabled' are required" });
  try {
    const result = await pool.query(
      `UPDATE users SET access_enabled = $1 WHERE id = $2
       RETURNING id, email, name, picture, access_enabled, created_at`,
      [enabled, id]
    );
    if (!result.rowCount) return res.status(404).json({ error: "User not found" });
    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to update access" });
  }
});

// ---- Start -----------------------------------------------------------------

// Idempotent schema touch-ups so new columns appear without a manual Neon step.
async function ensureSchema() {
  await pool.query("ALTER TABLE meetings ADD COLUMN IF NOT EXISTS transcript TEXT");
  await pool.query(`
    CREATE TABLE IF NOT EXISTS meeting_sessions (
      id SERIAL PRIMARY KEY,
      meeting_id INTEGER NOT NULL,
      user_email TEXT NOT NULL,
      conference_record TEXT NOT NULL,
      started_at TIMESTAMPTZ,
      ended_at TIMESTAMPTZ,
      transcript TEXT,
      summary TEXT,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE (meeting_id, conference_record)
    )
  `);

  // Per-user Jira deep-link base, e.g. https://acme.atlassian.net/browse/
  await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS jira_base_url TEXT");

  // Optional per-ticket metadata + cached cross-meeting journey synthesis.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS jiras (
      id SERIAL PRIMARY KEY,
      user_email TEXT NOT NULL,
      jira_key TEXT NOT NULL,
      title TEXT,
      journey_summary TEXT,
      journey_built_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE (user_email, jira_key)
    )
  `);

  // Many-to-many link between meetings and Jira tickets, with the AI-extracted
  // (or hand-edited) conclusion this meeting reached about that ticket.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS meeting_jiras (
      id SERIAL PRIMARY KEY,
      meeting_id INTEGER NOT NULL,
      user_email TEXT NOT NULL,
      jira_key TEXT NOT NULL,
      conclusion TEXT,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE (meeting_id, jira_key, user_email)
    )
  `);
  await pool.query("CREATE INDEX IF NOT EXISTS idx_meeting_jiras_key ON meeting_jiras (user_email, jira_key)");
  await pool.query("CREATE INDEX IF NOT EXISTS idx_meeting_jiras_meeting ON meeting_jiras (meeting_id)");
}

const port = Number(process.env.PORT) || 3000;
ensureSchema()
  .catch((err) => console.error("Schema check failed (continuing):", err.message))
  .finally(() =>
    app.listen(port, "0.0.0.0", () => console.log(`API listening on 0.0.0.0:${port}`))
  );
